### ISSUE TITLE
install [wis2box-ui] 

### ISSUE THREAD

**Issue by maixino** [wmo-im/wis2box-ui#32]
I am trying to install [wis2box-ui]  I have the error codes are as below.
Thank you in advance for your help.
pm ERR! Tracker "idealTree" already exists
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-07T16_56_27_864Z-debug-0.log
[root@localhost /]# npm run serve
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path //package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '//package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-07T16_57_41_237Z-debug-0.log

**Comment by chinedu117** [comment]
Same here.

Machine: ubuntu 22.04 LTS
node version: v16.18.0
npm: 8.19.2

Command: npm install

Error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @vue/cli-plugin-eslint@4.5.17
npm ERR! Found: @vue/cli-service@5.0.0-beta.7
npm ERR! node_modules/@vue/cli-service
npm ERR!   dev @vue/cli-service@"5.0.0-beta.7" from the root project
npm ERR!   peer @vue/cli-service@"^3.0.0 || ^4.0.0 || ^5.0.0-0" from @vue/cli-plugin-babel@5.0.0-beta.7
npm ERR!   node_modules/@vue/cli-plugin-babel
npm ERR!     dev @vue/cli-plugin-babel@"5.0.0-beta.7" from the root project
npm ERR!   2 more (@vue/cli-plugin-router, @vue/cli-plugin-vuex)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-eslint@4.5.17
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"~4.5.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @vue/cli-service@4.5.19
npm ERR! node_modules/@vue/cli-service
npm ERR!   peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-eslint@4.5.17
npm ERR!   node_modules/@vue/cli-plugin-eslint
npm ERR!     dev @vue/cli-plugin-eslint@"~4.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/chinedu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chinedu/.npm/_logs/2022-10-24T13_19_35_859Z-debug-0.log
```

Tried `npm install --force`  which worked but on running `npm run serve` i got
![Screenshot from 2022-10-24 14-01-47](https://user-images.githubusercontent.com/23460553/197536285-95a4149b-1ec7-48d9-afe3-6fc2a688f6d7.png)

**Comment by webb-ben** [comment]
The error you are seeing is because node-fibers is incompatible with node.js >= 16 (https://github.com/laverdet/node-fibers). 

wis2box-ui is not intended to be deployed standalone, but instead as a part of the [wis2box stack](https://github.com/wmo-im/wis2box/blob/aac3e5e57fd2b4227161c6cf5a99a9b185d8129d/docker/docker-compose.yml#L14-L21). 

It is recommended that wis2box-ui be run and installed using the pre-built docker images which serves wis2box as a web-pack. Will update the README to reflect this.
