### ISSUE TITLE
wis2box-ui to display info about dataset using new "dataset_info'-process in wis2box-api

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box-ui#82]
Currently the wis2box-ui primarily relies on information available from collections in pygeoapi with the exception being the "station_info"-process to retrieve information about stations for a dataset.

I would like to request for wis2box-ui to access a new "dataset_info"-process to be made available in next version of the wis2box-api

The dataset_info-process should be called once for each item in the discovery-metadata collection and provide a new button alongside the existing "explore" and "discovery-metadata" options, providing access to pop-up displaying the dataset_info content.

I will prepare a prototype of the new process for the wis2box-api  in a new branch "dataset_info" .

**Comment by webb-ben** [comment]
>  once for each item in the discovery-metadata collection

Can we make the urn be an optional argument of this process? Should no discovery-metadata urn be given, the process should return information about ALL items in the discovery-metadata collection

**Comment by maaikelimper** [comment]
OK good idea, I can design the function to return info about all datasets by default

**Comment by maaikelimper** [comment]
As mentioned in https://github.com/wmo-im/wis2box/issues/719
I've deployed an initial version of the "dataset-info" in the wis2box-api on our test-server

https://wis2box-test.wis2dev.io/oapi/processes/dataset-info

@webb-ben could you check how we could display this information in a user-friendly manner ?
