### ISSUE TITLE
Update wis2box-homepage

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box-ui#98]
The wis2box-ui homepage currently lists datasets along with some links

I'd like to propose to review the links and information displayed per configured dataset

- add metadata-id
- add link to messages, displaying `…/oapi/collections/messages/items?metadata_id=urn:wmo:md:etc`

Also, I would prefer to remove the top saying "home" and "documentation" as we really have only one page here and I would rather see the docs included in "Powered by wis2box" on the bottom

@C-Loftus @webb-ben : I am open to other suggestions, what do you think ?

**Comment by C-Loftus** [comment]
After discussion today, we discussed that we will need to have a translation for the new messages metadata button.

**Comment by maaikelimper** [comment]
This issue was mostly addressed in https://github.com/wmo-im/wis2box-ui/pull/95

outstanding to-do related to removing the nav-bar to go in a separate PR:
- remove link [community.wmo.int](http://community.wmo.int/) and replace with hyperlink to homepage of wis2box-ui and remove nav-bar
- the link to wis2box-documentation currently in the nav-bar to be moved to footer
